### ISSUE TITLE
react-native 0.42.3 would it be possible?

### ISSUE THREAD

**Issue by vinils** [ds300/react-native-typescript-transformer#27]
Hey guys, first of all I would like to thank you for your solution that is help me a lot!

I´m trying to integrate reactxp and expo but reactxp is running on react-native 0.42.3.
Does anyone knows if would it be possible to run react-native-typescript-transformer on react-native 0.42.3 and how i could make that?

Thanks in advance

**Comment by ds300** [comment]
Hi!

React-native versions less than 0.45 don't support custom source extensions, so react-native-typescript-transformer will not work out of the box. It is possible using [patch-package](https://github.com/ds300/patch-package), but you'd need to fiddle around with the react-native internals to figure out how to hack in support for .ts source extensions. I've done it before but couldn't share the code since I did it on a previous customer project.

**Comment by vinils** [comment]
Thank you very much for kindle share that with me... I´ll go on that!

**Comment by ds300** [comment]
I'm going to close this issue due to inactivity. Feel free to reopen it if you have further questions about using react-native versions before 0.45
