### ISSUE TITLE
Why JSX is not set to react-native?

### ISSUE THREAD

**Issue by henrikra** [ds300/react-native-typescript-transformer#46]
I noticed from JSX [docs](https://www.typescriptlang.org/docs/handbook/jsx.html) that JSX has also option `react-native` for it.

Here are all three different modes for JSX

> TypeScript ships with three JSX modes: preserve, react, and react-native. These modes only affect the emit stage - type checking is unaffected. The preserve mode will keep the JSX as part of the output to be further consumed by another transform step (e.g. Babel). Additionally the output will have a .jsx file extension. The react mode will emit React.createElement, does not need to go through a JSX transformation before use, and the output will have a .js file extension. The react-native mode is the equivalent of preserve in that it keeps all JSX, but the output will instead have a .js file extension.

So why `react-native-typescript-transformer` is telling us to configure JSX to `react` instead of `react-native`. Are there some drawbacks etc? :D

**Comment by ds300** [comment]
Hi Henrik,

Good question! I agree, the situation is a little confusing, and the reason
for it is historical rather than technical.

When React first appeared on the scene, most JS tooling was not compatible
with the JSX syntax. To mitigate this, people would only put JSX syntax in
files with the extension `.jsx`. Eventually the tooling caught up and now
most of us put JSX in `.js` files as though it were part of the ECMAScript
standard.

When TypeScript first added support for JSX, people were still using the
`.jsx` extension a lot, so the TS crew made `.tsx` files compile to `.jsx`
files. This is how the `--jsx react` option works.

The React Native ecosystem fully embraced the `.js` extension to the point
that the bundler `metro` doesn't even support loading `.jsx` files. This
posed a problem for people using TypeScript with React Native because
TypeScript *only* supported `.jsx` files. I can't actually remember how
people would use TypeScript with React Native back in those days, but it
was probably ugly.

The `--jsx react-native` option was added to to able to compile `.tsx`
files to ordinary `.js` files. It has no other difference to `--jsx react`.

So, as long as you're using `react-native-typescript-transformer` it
doesn't make a difference which option you use :)

**Comment by ds300** [comment]
Hi Henrik,

Good question! I agree, the situation is a little confusing, and the reason for it is historical rather than technical.

When React first appeared on the scene, most JS tooling was not compatible with the JSX syntax. To mitigate this, people would only put JSX syntax in files with the extension `.jsx`. Eventually the tooling caught up and now most of us put JSX in `.js` files as though it were part of the ECMAScript standard.

When TypeScript first added support for JSX, people were still using the `.jsx` extension a lot, so the TS crew made `.tsx` files compile to `.jsx` files. This is how the `--jsx react` option works.

The React Native ecosystem fully embraced the `.js` extension to the point that the bundler `metro` doesn't even support loading `.jsx` files. This posed a problem for people using TypeScript with React Native because TypeScript *only* supported `.jsx` files. I can't actually remember how people would use TypeScript with React Native back in those days, but it was probably ugly.

The `--jsx react-native` option was added to to able to compile `.tsx` files to ordinary `.js` files. It has no other difference to `--jsx react`.

So, as long as you're using `react-native-typescript-transformer` it doesn't make a difference which option you use :)

**Comment by henrikra** [comment]
Great explanation! So would it makes sense to change readme to use `react-native` if it doesn't matter and it semantically more relevant? :D

**Comment by ds300** [comment]
Sure, makes sense. I'll do that.

**Comment by ds300** [comment]
Hmm actually I misremembered what the `react-native` option does, which is highly embarrassing since I wrote it 🤦‍♀️  

It actually leaves the JSX untouched, which makes it identical to the `preserve` option except that it emits `.js` files instead of `.jsx` files. This is already mentioned in the README so I'll leave it untouched.

**Comment by henrikra** [comment]
You are right! I didn't notice it. Thanks for your help :)

**Comment by youngjuning** [comment]
0.57.3 is not support

**Comment by fantasy525** [comment]
> hich would ca

thank you ,I set jsx 'react-native',but i got a error:can't find the variable React;
so I set jsx 'react',it works!
